### ISSUE TITLE
🐛 Bug: README.md badge links have visual underlines

### ISSUE THREAD

**Issue by JoshuaKGoldberg** [JoshuaKGoldberg/create-typescript-app#1027]
### Bug Report Checklist

- [X] I have tried restarting my IDE and the issue persists.
- [X] I have pulled the latest `main` branch of the repository.
- [X] I have [searched for related issues](https://github.com/JoshuaKGoldberg/create-typescript-app/issues?q=is%3Aissue) and found none that matched my issue.

### Expected

I like a clean README.md. No weird little visual inconsistencies around link underlines or whatnot.

### Actual

There are little link underlines outside the badge images in generated README.mds 😬 

![Screenshot of the dark mode README showing underlines between badge images](https://github.com/JoshuaKGoldberg/create-typescript-app/assets/3335181/12b13314-3fe1-4ad4-aa9a-a9cca76a1a87)

![Screenshot of the light mode README showing underlines between badge images](https://github.com/JoshuaKGoldberg/create-typescript-app/assets/3335181/4252544b-60e6-4bd2-aed1-e1deabb68345)

### Additional Info

GitHub recently changed markdown docs to render the underlines by default (good! accessibility!). This was an issue on hover for links even before then.

**Comment by JoshuaKGoldberg** [comment]
👋 @5hraddha, happy you're interested in this! I don't use any kind of issue claiming system: https://github.com/JoshuaKGoldberg/create-typescript-app/blob/62281d8a0c16872eb16bbd12ce44d145e5080748/.github/CONTRIBUTING.md#issue-claiming. But feel free to send a PR if you've got a fix. I'd recommend reading through that contributing guide and its linked development guide to answer common questions about how to send PRs. Cheers!

**Comment by 5hraddha** [comment]
Sure, @JoshuaKGoldberg . That helps. Thank you!
