### ISSUE TITLE
🛠 Tooling: Lack of indentation in generated README.md all-contributors badge

### ISSUE THREAD

**Issue by JoshuaKGoldberg** [JoshuaKGoldberg/create-typescript-app#1041]
### Bug Report Checklist

- [X] I have tried restarting my IDE and the issue persists.
- [X] I have pulled the latest `main` branch of the repository.
- [X] I have [searched for related issues](https://github.com/JoshuaKGoldberg/create-typescript-app/issues?q=is%3Aissue) and found none that matched my issue.

### Overview

When you first `--mode create` a repository using `create-typescript-app` right now, if `--base everything` is specified, this is what the badges in the README.md roughly look like:

```md
<p align="center">
	<!-- prettier-ignore-start -->
	<!-- ALL-CONTRIBUTORS-BADGE:START - Do not remove or modify this section -->
<a href="#contributors" target="_blank"><img alt="All Contributors: 1 👪" src="https://img.shields.io/badge/all_contributors-1_👪-21bb42.svg" /></a>
<!-- ALL-CONTRIBUTORS-BADGE:END -->
	<!-- prettier-ignore-end -->
	<a href="https://codecov.io/gh/asdf/asdf" target="_blank"><img alt="Codecov Test Coverage" src="https://codecov.io/gh/asdf/asdf/branch/main/graph/badge.svg"/></a>
	<a href="https://github.com/asdf/asdf/blob/main/.github/CODE_OF_CONDUCT.md" target="_blank"><img alt="Contributor Covenant" src="https://img.shields.io/badge/code_of_conduct-enforced-21bb42" /></a>
	<a href="https://github.com/asdf/asdf/blob/main/LICENSE.md" target="_blank"><img alt="License: MIT" src="https://img.shields.io/github/license/asdf/asdf?color=21bb42"></a>
	<img alt="Style: Prettier" src="https://img.shields.io/badge/style-prettier-21bb42.svg" />
	<img alt="TypeScript: Strict" src="https://img.shields.io/badge/typescript-strict-21bb42.svg" />
	<img alt="npm package version" src="https://img.shields.io/npm/v/create-typescript-app?color=21bb42" />
</p>
```

The indentation situation was made better in #1038, but not completely perfect. Note the lack of indentation in the all-contributors `<a ...` and `<!-- ALL-CONTRIBUTORS-BADGE:END -->` lines. It would be nice if those two lines could be indented consistently with the rest of them...
1. `<a ...`: probably a matter of updating the `.all-contributorsrc` badge template?
2. `<!-- ALL-CONTRIBUTORS-BADGE:END -->`: I don't know and haven't looked into it much. Maybe a bug / feature request to file on allcontributors in some way? Maybe?

This is pretty low priority as it doesn't actually impact users. But if anybody is motivated and wants to take a look, I'd love to get this ironed out. 😄 

### Additional Info

Quick shell script I'm using to create a repo within the `create-typescript-app` project:

```plaintext
mkdir temp
cd temp
node ../bin/index.js --base everything --mode create --skip-github-api --title asdf --owner asdf --repository asdf --description asdf
```

**Comment by jaas666** [comment]
I was able to find where to fix the `href` indentation and opened #1054 for it, but can't for the life of me find where the `<!-- ALL-CONTRIBUTORS-BADGE:END -->` is being changed.

My guess is that something somewhere is formatting the README.md. I was able to grab a clip showing the file being created correctly then the formatting applied. Hopefully this gives a clue as to where to look.

https://github.com/JoshuaKGoldberg/create-typescript-app/assets/30204147/5cecd98f-2240-4bbc-9789-216d83a9890f
