### ISSUE TITLE
🐛 Bug: Migrating a non-JoshuaKGoldberg repo creates the wrong owners for JoshuaKGoldberg actions

### ISSUE THREAD

**Issue by JoshuaKGoldberg** [JoshuaKGoldberg/create-typescript-app#1043]
### Bug Report Checklist

- [X] I have tried restarting my IDE and the issue persists.
- [X] I have pulled the latest `main` branch of the repository.
- [X] I have [searched for related issues](https://github.com/JoshuaKGoldberg/create-typescript-app/issues?q=is%3Aissue) and found none that matched my issue.

### Expected

Running `--mode migrate` on an existing repo under a owner other than `JoshuaKGoldberg` should still set up actions like `JoshuaKGoldberg/release-it-action` under the proper owners.

### Actual

I'd missed in https://github.com/omnidan/node-emoji/pull/142 that two actions were set up incorrectly:

* `omnidan/all-contributors-auto-action` was configured instead of `JoshuaKGoldberg/all-contributors-auto-action`
* `omnidan/release-it-action` was configured instead of `JoshuaKGoldberg/release-it-action`

**Comment by jaas666** [comment]
I was able to reproduce this bug but can't figure out why it happens.
The only thing that caught my eye was this line that's using string literals instead of double quotes, although I'm pretty sure that shouldn't cause the issue.

I'd still change it to double quotes just to pass the OCD test. 🤣

 https://github.com/JoshuaKGoldberg/create-typescript-app/blob/c347e0b20f1bc7ba4cfaab71e7927517a1ff6f3f/src/steps/writing/creation/dotGitHub/createWorkflows.ts#L87

**Comment by jaas666** [comment]
I think I found the issue:
https://github.com/JoshuaKGoldberg/create-typescript-app/blob/c347e0b20f1bc7ba4cfaab71e7927517a1ff6f3f/src/steps/updateLocalFiles.ts#L17

**Comment by JoshuaKGoldberg** [comment]
Hmm, yeah, it's tricky. I never liked having that specific `console-fail-test` exclusion in there. Very brittle.

The array of replacements including that entry go down to [`replace-in-file`](https://www.npmjs.com/package/replace-in-file), which has a [callback option for `to`](https://www.npmjs.com/package/replace-in-file#using-callbacks-for-to). Maybe a callback that doesn't change a known list of good names (`console-fail-test`, `all-contributors-auto-action`, ...)?

And/or: maybe _only_ replace a repo path like `JoshuaKGoldberg/...` if the `...` is `create-typescript-app`? So `JoshuaKGoldberg/create-typescript-app` would be replaced, but not `JoshuaKGoldberg/console-fail-test`, `JoshuaKGoldberg/all-contributors-auto-action`, etc.?
