### ISSUE TITLE
📝 Documentation: Clarify how to operate the Clack prompt

### ISSUE THREAD

**Issue by johnnyreilly** [JoshuaKGoldberg/create-typescript-app#1121]
### Bug Report Checklist

- [X] I have pulled the latest `main` branch of the repository.
- [X] I have [searched for related issues](https://github.com/JoshuaKGoldberg/create-typescript-app/issues?q=is%3Aissue) and found none that matched my issue.

### Overview

![image displaying a screenshot of the terminal with a message I am unclear on](https://github.com/JoshuaKGoldberg/create-typescript-app/assets/1010525/0e0b9e74-19b7-4f73-a407-505b80edfbcb)

As you can probably gather, I didn't work out how and ended up with everything to my chagrin!

### Additional Info

n/a

**Comment by JoshuaKGoldberg** [comment]
Backing context: That prompt UI comes from Clack. 
Direct answer: You can press <kbd>↑</kbd> and <kbd>↓</kbd> on the keyboard to change the selected item, then <kbd>space</kbd> to select.

<img width="951" alt="Screenshot of the Clack prompt from create-typescript-app. A first item (Add all-contributors to track contributions and display them in a README.md table. (--exclude-all-contributors)) is not selected. A second item (Add a GitHub Actions workflow to verify that PRs match an expected format.) is selected." src="https://github.com/JoshuaKGoldberg/create-typescript-app/assets/3335181/6a18ab0e-ae71-4e5b-83f4-8af4478ca891">

Was this not clear from the prompt? Do you think there should be some text to explain it?

**Comment by johnnyreilly** [comment]
> Was this not clear from the prompt? Do you think there should be some text to explain it?

I can only say it wasn't clear to me.  It's possible everyone else knows that this is how you do it:

> You can press ↑ and ↓ on the keyboard to change the selected item, then space to select.

I'd encourage including the text above

**Comment by JoshuaKGoldberg** [comment]
👍 makes sense, I agree it's not super intuitive as is. Thanks for calling it out! Accepting PRs to add a small indication to the prompt.

**Comment by johnnyreilly** [comment]
I did try and work out how to add it just now but couldn't work it out. Can you advise where i'd tweak?

**Comment by JoshuaKGoldberg** [comment]
> but couldn't work it out

err, what do you mean by this?

**Comment by johnnyreilly** [comment]
nevermind - found it
