### ISSUE TITLE
🐛 Bug: Re-run command includes unnecessary true value for boolean options

### ISSUE THREAD

**Issue by JoshuaKGoldberg** [JoshuaKGoldberg/create-typescript-app#1129]
### Bug Report Checklist

- [X] I have tried restarting my IDE and the issue persists.
- [X] I have pulled the latest `main` branch of the repository.
- [X] I have [searched for related issues](https://github.com/JoshuaKGoldberg/create-typescript-app/issues?q=is%3Aissue) and found none that matched my issue.

### Expected

The re-run command when you cancel or complete `npx create-typescript-app` should be as minimal as possible. Boolean options set to true, such as `offline`, can just be `--offline`. No need for `--offline true`. They mean the same thing.

### Actual

Alas, the rerun suggestion does print `--offline true` and similar:

```plaintext
npx create-typescript-app --mode create --offline
┌  ✨ Welcome to create-typescript-app 1.50.0! ✨
│
│  ⚠️ This template is early stage, opinionated, and not endorsed by the TypeScript team. ⚠️
│  ⚠️ If any tooling it sets displeases you, you can always remove that portion manually. ⚠️
│
■  What organization or user will the repository be under?
│
│
●  Tip: to run again with the same input values, use: npx create-typescript-app --mode undefined --offline true --skip-all-contributors-api true --skip-github-api true
│
└  Operation cancelled. Exiting - maybe another time? 👋
```

**Comment by DerTimonius** [comment]
I will look into it! 🙂
