### ISSUE TITLE
🐛 Bug: Is CTA adding more checks than there are workflows for it?

### ISSUE THREAD

**Issue by johnnyreilly** [JoshuaKGoldberg/create-typescript-app#1171]
### Bug Report Checklist

- [X] I have tried restarting my IDE and the issue persists.
- [X] I have pulled the latest `main` branch of the repository.
- [X] I have [searched for related issues](https://github.com/JoshuaKGoldberg/create-typescript-app/issues?q=is%3Aissue) and found none that matched my issue.

### Expected

Heya!  

So I'm hacking away at my side project here: https://github.com/johnnyreilly/schemar/pull/1

And I noticed on the PR that there were checks for workflows that I don't have in my repo; a bunch of the lint_knip / lint_markdown etc workflows

Given I don't have those in my repo, I was surprised they showed up in GitHub.  Regrettably I can't remember if those workflow files originally existed or if I deleted them.  (Makes me think it'd be handy to have a metadata file that shows how a project was initialised or something)

### Actual

![screenshot of github showing checks that don't have corresponding workflows](https://github.com/JoshuaKGoldberg/create-typescript-app/assets/1010525/8946812f-d060-4a72-b29f-84cf1d4c114b)

### Additional Info

This might be user error; not sure.

**Comment by JoshuaKGoldberg** [comment]
Ah, yes, this is a bug. Good catch. Workflow _files_ are created conditionally based on options:

https://github.com/JoshuaKGoldberg/create-typescript-app/blob/01704e906969fc3cba8be9618e6e097ec3760cd4/src/steps/writing/creation/dotGitHub/createWorkflows.ts#L119-L120

...but _branch protection settings_ are all always created:

https://github.com/JoshuaKGoldberg/create-typescript-app/blob/70d6937a82040ab9dd49e28878105140645cce3a/src/steps/initializeGitHubRepository/initializeBranchProtectionSettings.ts#L26-L31 

The `initializeBranchProtectionSettings` function should be updated to only create branch protections needed per `options`. Thanks for filing!
