### ISSUE TITLE
🚀 Feature: Use ESLint flat config

### ISSUE THREAD

**Issue by JoshuaKGoldberg** [JoshuaKGoldberg/create-typescript-app#1212]
### Bug Report Checklist

- [X] I have tried restarting my IDE and the issue persists.
- [X] I have pulled the latest `main` branch of the repository.
- [X] I have [searched for related issues](https://github.com/JoshuaKGoldberg/create-typescript-app/issues?q=is%3Aissue) and found none that matched my issue.

### Overview

https://eslint.org/docs/latest/use/configure/configuration-files-new: ESLint's new "flat config" format is going to be the main -> only way to configure ESLint soon. So this template should use that!

### Additional Info

Adding to the [General Simplification milestone](https://github.com/JoshuaKGoldberg/create-typescript-app/milestone/3) as it'd allow the repo to get rid of the `.eslintignore` file.

...and also marking this as blocked on typescript-eslint supporting ESLint flat config. Which we're still blocked on as of filing this issue. https://github.com/typescript-eslint/typescript-eslint/issues/7694

**Comment by sys13** [comment]
This is no longer blocked by typescript-eslint

**Comment by JoshuaKGoldberg** [comment]
Ha, you're right - thanks for the spot. Out of the plugins this depends on...

- [x] [`@typescript-eslint`](https://github.com/typescript-eslint/typescript-eslint)
- [ ] [`eslint-comments`](https://github.com/eslint-community/eslint-plugin-eslint-comments)
- [x] [`jsdoc`](https://github.com//gajus/eslint-plugin-jsdoc)
- [ ] [`jsonc`](https://github.com/ota-meshi/eslint-plugin-jsonc)
- [x] [`markdown`](https://github.com/eslint/eslint-plugin-markdown)
- [x] [`n`](https://github.com/eslint-community/eslint-plugin-n)
- [ ] [`package-json`](https://github.com/JoshuaKGoldberg/eslint-plugin-package-json) _(oops, there's a PR already that I missed!)_
- [x] [`perfectionist`](https://github.com/azat-io/eslint-plugin-perfectionist)
- [x] [`regexp`](https://github.com/ota-meshi/eslint-plugin-regexp)
- [x] [`vitest`](https://github.com/veritem/eslint-plugin-vitest)
- [ ] [`yml`](https://github.com/ota-meshi/eslint-plugin-yml)

...so it's still blocked - just on other plugins. I'll try to get to sending issues/PRs within the week or so for any that still need it.

**Comment by sys13** [comment]
Amazing, thanks for looking into each of the packages!

**Comment by JoshuaKGoldberg** [comment]
Thanks to a PR review from @voxpelli for the last one, `eslint-comments`, this is ready to do!

**Comment by JoshuaKGoldberg** [comment]
D'oh, I'd missed from the list that `eslint-plugin-deprecation` still needs it. Will draft a PR now but it will be blocked on that one.
