### ISSUE TITLE
🚀 Feature: Move some lint rules over to no-autofix

### ISSUE THREAD

**Issue by danvk** [JoshuaKGoldberg/create-typescript-app#1245]
### Bug Report Checklist

- [X] I have tried restarting my IDE and the issue persists.
- [X] I have pulled the latest `main` branch of the repository.
- [X] I have [searched for related issues](https://github.com/JoshuaKGoldberg/create-typescript-app/issues?q=is%3Aissue) and found none that matched my issue.

### Overview

When I write:

```ts
let x: string | null = null;
```

eslint autofixes the `let` to `const`. I find this to be incredibly unhelpful. If I wrote `let`, it's more likely that I haven't reassigned the variable _yet_. By auto-fixing it to `const`, eslint will produce a TypeScript error later, when I do reassign `x`, and this one can't be autofixed.

Of course, I _do_ want an eslint error for a `let` variable that's never reassigned. I just don't want autofix.

I'm not aware of any built-in way to get this behavior with eslint, but it's exactly what the [`no-autofix` plugin](https://github.com/aladdin-add/eslint-plugin/tree/master/packages/no-autofix) is designed to do. They specifically mention the `prefer-const` rule as their motivating example.

Since this repo's `.eslintrc.cjs` file is so complex, swapping in `no-autofix/prefer-const` isn't that straightforward (you have to do it in a few places depending on the file type). It would be nice if this starter kit set up no-autofix and had a centralized place in its `.eslintrc.cjs` to indicate that you'd prefer the no-autofix version of a rule.

### Additional Info

TBH I'm kind of baffled how anyone writes code with the autofix for `prefer-const` on!

I've also disabled autofix for `@typescript-eslint/no-confusing-void-expression`. I find the rule useful but its autofix is horrible:

```
- () => fn()
+ () => { fn() }
```

This happens if I haven't defined `fn()` yet, or haven't defined it fully enough for it to have an inferred return type. If I'm defining `fn()` then the autofix happens offscreen and completely changes the behavior. Yuck!

**Comment by JoshuaKGoldberg** [comment]
> how anyone writes code with the autofix for `prefer-const` on!

😄 out of curiosity, how often are your files being saved? Do you have your editor set up to always save on an interval / when typing is done, and/or are you manually saving frequently?

I personally haven't had this pain because I generally only save after I'm done with a block - which means my variables aren't violating by the time I'm done with them.

(I also write `let` exceedingly rarely, maybe that's just me)

> `@typescript-eslint/no-confusing-void-expression`

Maybe this is a good feature request for the rule? To only auto-fix if the type is known (not `error`? Similar to #8231, but for this rule specifically? Thoughts?

**Comment by danvk** [comment]
> > how anyone writes code with the autofix for `prefer-const` on!
> 
> 😄 out of curiosity, how often are your files being saved? Do you have your editor set up to always save on an interval / when typing is done, and/or are you manually saving frequently?

Maybe that's it. I used a [programming language / IDE][1] many, many years ago that crashed a lot and it left me with a lifelong habit of compulsively hitting <kbd>Cmd</kbd><kbd>S</kbd>. I do this subconsciously so I'm not 100% how often I save, but probably every line if not more frequently.

[1]: https://en.wikipedia.org/wiki/Xojo

**Comment by JoshuaKGoldberg** [comment]
Coming back after a while: this isn't a common ask I've seen, so I think it'd be best left up to the individual repositories. Thanks though!
