### ISSUE TITLE
🐛 Bug: "Initializing GitHub repository" freezes if manual Git commit unlock passphrase needed

### ISSUE THREAD

**Issue by JoshuaKGoldberg** [JoshuaKGoldberg/create-typescript-app#1275]
### Bug Report Checklist

- [X] I have tried restarting my IDE and the issue persists.
- [X] I have pulled the latest `main` branch of the repository.
- [X] I have [searched for related issues](https://github.com/JoshuaKGoldberg/create-typescript-app/issues?q=is%3Aissue) and found none that matched my issue.

### Expected

Some users set up an [SSH key passphrase](https://docs.github.com/en/authentication/connecting-to-github-with-ssh/working-with-ssh-key-passphrases) for their Git commits. Sometimes those phrases are needed to be manually input for making a Git commit.

In that case, the `create-typescript-app` CLI should allow the user to enter their passphrase when making a commit.

### Actual

The prompt sticks to _"Initializing GitHub repository..."_ and doesn't accept the passphrase input.

![Terminal screenshot showing "Initializing GitHub repository..." and part of a "Please enter the passphrase to unlock..." notice](https://github.com/JoshuaKGoldberg/create-typescript-app/assets/3335181/550df36d-d08b-45ea-9e08-6f0d4d0c4344)

_(I think all the info there is public, but blurring just in case...)_

### Additional Info

I'd originally set mine up to be automatic but at some point it switched to needing manual re-entry every hour or so. I've been meaning to fix that for ages... but hey, the result is I found this bug. So that's nice!

I tried passing in `"stdio": "pipe"` as `$` options and that did seem to allow typing in. But some characters kept getting dropped I think. passphrases were getting reported as wrong, and sometimes I needed to press <kbd>Enter</kbd> multiple times... maybe an issue to be filed on Clack?

**Comment by omnidan** [comment]
A workaround I found until this is fixed, is running the script with the `--skip-github-api` option.

That will prevent it from going into the "Initializing GitHub repository" step and instead print a list of commands to manually run to initialize the repository.

Unfortunately, running these steps in the recommended order also did not seem to work, as they only work on existing repositories (I got an error from GitHub `Cannot update default branch for an empty repository. Please init the repository and push first.`).

What I did then to make it work is first manually create the repository using the steps from GitHub, but adding all code from the repo to it already, then pushing it, and then running the `create-typescript-app` command from the first recommended step again. Then all that's left to do is the following:

- enable the GitHub apps:
   - Codecov (https://github.com/apps/codecov)
   - Renovate (https://github.com/apps/renovate)
- populate the secrets:
   - ACCESS_TOKEN (a GitHub PAT with repo and workflow permissions)
   - NPM_TOKEN (an npm access token with automation permissions)

It's a bit more complicated than just running a command, but you still get to use most of the template to get it up and running, just the GitHub repo needs to be set up manually.
