### ISSUE TITLE
🛠 Tooling: Run `node lib/index.js --version` instead of `node lib/index.js`

### ISSUE THREAD

**Issue by danvk** [JoshuaKGoldberg/create-typescript-app#1353]
### Bug Report Checklist

- [X] I have tried restarting my IDE and the issue persists.
- [X] I have pulled the latest `main` branch of the repository.
- [X] I have [searched for related issues](https://github.com/JoshuaKGoldberg/create-typescript-app/issues?q=is%3Aissue) and found none that matched my issue.

### Overview

The `build.yml` workflow tries to run `node lib/index.js`. But there's no reason to expect that invoking a command with no arguments is valid.

Running something like

    node lib/index.js --version

might be safer. Of course, that assumes the program accepts command line arguments!

### Additional Info

https://github.com/danvk/literate-ts/actions/runs/8072807240/job/22055278339?pr=246

**Comment by JoshuaKGoldberg** [comment]
Hmm, yeah, super interesting. It's not 100% that every command would have a no-args-required `--version`... but at the very least, maybe it'd be reasonable as an override for _this_ repository?

**Comment by JoshuaKGoldberg** [comment]
I think it'd be a good idea to add this in as an override for create-typescript-app. Specifically, that'd look like:

* `.github/workflows/ci.yml`'s `build` task would have `- run: node ./bin/index.js --version`
* `script/__snapshots__/migrate-test-e2e.ts.snap` would have an added bit of diff to mention that
