### ISSUE TITLE
🚀 Feature: a github action to track bundle size

### ISSUE THREAD

**Issue by dlvhdr** [JoshuaKGoldberg/create-typescript-app#1398]
### Bug Report Checklist

- [X] I have pulled the latest `main` branch of the repository.
- [X] I have [searched for related issues](https://github.com/JoshuaKGoldberg/create-typescript-app/issues?q=is%3Aissue) and found none that matched my issue.

### Overview

A github action that comments on the PR with a diff of the current bundle size vs the one in the base.
Something like https://github.com/Schniz/benchy-action?tab=readme-ov-file or bundlemon.

**Comment by JoshuaKGoldberg** [comment]
Hmm, this is an interesting idea, thanks for filing... I personally don't find much benefit from these, but I know that other folks do.

My personal leanings are to say 'no' on the grounds of this only being applicable to _some_ TypeScript packages. But I might be wrong there - leaving open in discussion in case you / anybody wants to push back on that.

**Comment by dlvhdr** [comment]
Not sure either if there's a solution that fits every project. I did see https://github.com/preactjs/compressed-size-action. 

Anyway I have something similar in my work repo, because we recently included fakerjs in our bundle by mistake.

**Comment by JoshuaKGoldberg** [comment]
Just following up: this really is a nice thing for a lot of projects, but is too specific for `create-typescript-app` at the moment. I'm going to go ahead and close this out. Thanks for posting!
