### ISSUE TITLE
🛠 Tooling: Find a cleaner approach to temporarily disabling branch protections

### ISSUE THREAD

**Issue by JoshuaKGoldberg** [JoshuaKGoldberg/create-typescript-app#145]
### Bug Report Checklist

- [X] I have tried restarting my IDE and the issue persists.
- [X] I have pulled the latest `main` branch of the repository.
- [X] I have [searched for related issues](https://github.com/JoshuaKGoldberg/template-typescript-node-package/issues?q=is%3Aissue) and found none that matched my issue.

### Overview

#144 added scripts to the release workflow that:

1. Before running [release-it](https://github.com/release-it/release-it), delete any branch protections on `main`
2. Afterwards, manually create branch protections on `main`

The branch protections are roughly a copy & paste of the `script/setup.js` settings. It would be nice to use some automation that can remember the existing branch protections without having to copy & paste in source code.

### Additional Info

I'd tried https://github.com/benjefferies/branch-protection-bot but looks like it's not as comprehensive (https://github.com/benjefferies/branch-protection-bot/issues/30). That general idea would be nice though.

**Comment by RebeccaStevens** [comment]
Apparently with an admin PAT token, you can push by-passing branch protection rules.

Note: You need to set `persist-credentials: false` for `actions/checkout@v3`.

There also seems to be ways to allow GitHub Apps to by-pass branch protection rules. This isn't currently possible with actions.

More info here: https://github.com/orgs/community/discussions/13836

**Comment by jsjoeio** [comment]
Would like this as well! I thought it was very weird to see it disabled then re-enabled 😅

**Comment by JoshuaKGoldberg** [comment]
We should note that Changesets _might_ make this unnecessary (#297). @andarist and I were going to look roughly this week! I'm very hopeful.

**Comment by JoshuaKGoldberg** [comment]
I ended up sticking with the delete-and-recreate strategy in https://github.com/JoshuaKGoldberg/release-it-action -> #927 😞. If there's a cleaner approach I'd be _very_ open to an issue in release-it-action. 

Looking at the alternatives mentioned so far:

* `push-protected` action: it also has to recreate branch protections (https://github.com/CasperWA/push-protected/blob/4ba0a55ae39e9a2b395695a7d40d3b29bff32324/push_action/run.py)
* using an admin PAT: that ... scares me.

I might be totally off-base here 😄 so again please do file an issue if you've got a suggestion for a better way!
