### ISSUE TITLE
🚀 Feature: Add Vitest VS Code Extension to extensions.json?

### ISSUE THREAD

**Issue by johnnyreilly** [JoshuaKGoldberg/create-typescript-app#1628]
### Bug Report Checklist

- [X] I have pulled the latest `main` branch of the repository.
- [X] I have [searched for related issues](https://github.com/JoshuaKGoldberg/create-typescript-app/issues?q=is%3Aissue) and found none that matched my issue.

### Overview

I wanted to be able to run tests in VS Code.  For that I found I needed to install the [Vitest VS Code extension](https://marketplace.visualstudio.com/items?itemName=vitest.explorer). I made the following change to my own projects `extensions.json` to recommend this to users:

```diff
+  "vitest.explorer"
```

Would it be worth including that in CTA for users writing tests?

**Comment by JoshuaKGoldberg** [comment]
Oh hey this is pretty sweet! I'd missed it. Yeah, yes please!

**Comment by johnnyreilly** [comment]
Implementing now - fun fact: GitHub CoPilot suggested @orta's `"orta.vscode-jest"` before I got to the `"vitest.explorer"` 😄
