### ISSUE TITLE
🚀 Feature: Test files shouldn't be published

### ISSUE THREAD

**Issue by JoshuaKGoldberg** [JoshuaKGoldberg/create-typescript-app#1629]
### Bug Report Checklist

- [X] I have pulled the latest `main` branch of the repository.
- [X] I have [searched for related issues](https://github.com/JoshuaKGoldberg/create-typescript-app/issues?q=is%3Aissue) and found none that matched my issue.

### Overview

Right now, CTA repos publish all files under `lib/`:

https://github.com/JoshuaKGoldberg/create-typescript-app/blob/9034d25992800bc8f7891f9cac4bfdf1e2f8c6b2/package.json#L17-L23

...including `*.test.*` files. 😬. That's a lot of extra file size on published packages for no real gain. I think `*.test.*` files should be excluded from the published outputs. 

### Additional Info

I'd previously fixed this in 7cdb836250404b8a3048c1ef281ca468320a2e5f, but at some point switched away from `.npmignore` files and lost that.

💖

**Comment by johnnyreilly** [comment]
Is this as simple as re-introducing an `.npmignore` with this content?:

```bash
*.test.*
```

**Comment by JoshuaKGoldberg** [comment]
I think so!

**Comment by johnnyreilly** [comment]
Let me PR - just heading out so hopefully tomorrow
