### ISSUE TITLE
🚀 Feature: Add a --privacy flag for publishConfig > access

### ISSUE THREAD

**Issue by JoshuaKGoldberg** [JoshuaKGoldberg/create-typescript-app#665]
### Bug Report Checklist

- [X] I have tried restarting my IDE and the issue persists.
- [X] I have pulled the latest `main` branch of the repository.
- [X] I have [searched for related issues](https://github.com/JoshuaKGoldberg/template-typescript-node-package/issues?q=is%3Aissue) and found none that matched my issue.

### Overview

Publish configs were added in #465 -> #466. It should be that if you initialize a new repository and add the requisite tokens, publishing should work immediately. But, per https://twitter.com/malloc007/status/1693623834509824120, the lack of `access: true` means packages might not immediately publish well.

Let's add a `--privacy` flag that defaults to `"public"`. That way users have control over whether the package is public or private, and it's surfaced in the docs.

### Additional Info

Thanks @ryota-murakami for speaking up! ❤️

**Comment by ryota-murakami** [comment]
@JoshuaKGoldberg Recently, I've gotten used to npm publish and release-it, and I've come to think that this is not an issue at all.
Can I close it?

**Comment by JoshuaKGoldberg** [comment]
Sure, works for me!

**Comment by JoshuaKGoldberg** [comment]
Ah, I actually hit this today:

1. I created a new package
2. I added GitHub and npm tokens
3. Error: `Can't generate provenance for new or private package, you must set `access` to public.`

I'll add this feature in after all. 😄
