### ISSUE TITLE
🚀 Feature: Add a --help CLI option

### ISSUE THREAD

**Issue by JoshuaKGoldberg** [JoshuaKGoldberg/create-typescript-app#703]
### Bug Report Checklist

- [X] I have tried restarting my IDE and the issue persists.
- [X] I have pulled the latest `main` branch of the repository.
- [X] I have [searched for related issues](https://github.com/JoshuaKGoldberg/template-typescript-node-package/issues?q=is%3Aissue) and found none that matched my issue.

### Overview

Now that `npx template-typescript-node-package` is a supported -even recommended- use case, folks will want to be able to run `npx template-typescript-node-package --help`. Let's have it print out, for each of the available CLI options, what they do. Also the package version

Vaguely:

```shell
npx template-typescript-node-package --help

✨ template-typescript-node-package v1.2.3 ✨

A quickstart-friendly TypeScript template with comprehensive formatting, linting, releases, testing, and other great tooling built-in.

--base: Whether to scaffold the repository with:
  - `everything` that comes with the template _(recommended)_
  - `minimum` amounts of tooling, essentially opting out of everything
  - `prompt` for which portions to exclude
--create-repository: Whether to create a corresponding repository on github.com (if it doesn't yet exist)
...

👉 See https://github.com/JoshuaKGoldberg/template-typescript-node-package for more documentation.
```

### Additional Info

See https://github.com/JoshuaKGoldberg/template-typescript-node-package/blob/77c10eb9d8dd384ae8e6417d26b92211185b6487/docs/Options.md for descriptions of existing CLI flags. You can directly copy & paste from there. 

I'd also suggest running `parseArgs` to make sure Options.md isn't missing any options (it's entirely possible I forgot about one...).

Arguments are first parsed here: https://github.com/JoshuaKGoldberg/template-typescript-node-package/blob/0307eba66fe59c3a89a189352fd4797aad37736f/src/bin/index.ts#L34-L40

I think you'll want to add a `--help` arg there with a `-h` shorthand. See https://nodejs.org/api/util.html#utilparseargsconfig for examples of `short`.

**Comment by dominicduffin1** [comment]
I'll have a go at this!
