### ISSUE TITLE
🚀 Feature: Add npm version badge to README.md (and template)

### ISSUE THREAD

**Issue by JoshuaKGoldberg** [JoshuaKGoldberg/create-typescript-app#730]
### Bug Report Checklist

- [X] I have tried restarting my IDE and the issue persists.
- [X] I have pulled the latest `main` branch of the repository.
- [X] I have [searched for related issues](https://github.com/JoshuaKGoldberg/create-typescript-app/issues?q=is%3Aissue) and found none that matched my issue.

### Overview

I don't remember why I didn't add a README.md badge that includes the npm version:

https://shields.io/badges/endpoint-badge

```html
<a href="https://npmjs.com/package/create-typescript-app">
  <img alt="npm package version" src="https://img.shields.io/npm/v/create-typescript-app?color=21bb42">
</a>
```

<a href="https://npmjs.com/package/create-typescript-app">
  <img alt="npm package version" src="https://img.shields.io/npm/v/create-typescript-app?color=21bb42">
</a>

### Additional Info

In addition to adding this in the repo's README.md, it'll need to be added to the templating used for setting up other repos. Search files for `readme` _(case insensitive)_ in their title to see where that's done.

**Comment by rj2704** [comment]
Hi @JoshuaKGoldberg, I can fix this issue. You can assign it to me.

**Comment by JoshuaKGoldberg** [comment]
@rj2704 I don't use any assignment/claiming processes in this repo - and just realized it's not documented! See #741 (filed just now). Thanks!
