### ISSUE TITLE
🛠 Tooling: Rename *:test to test:*

### ISSUE THREAD

**Issue by JoshuaKGoldberg** [JoshuaKGoldberg/create-typescript-app#786]
### Bug Report Checklist

- [X] I have tried restarting my IDE and the issue persists.
- [X] I have pulled the latest `main` branch of the repository.
- [X] I have [searched for related issues](https://github.com/JoshuaKGoldberg/create-typescript-app/issues?q=is%3Aissue) and found none that matched my issue.

### Overview

Right now, "end-to-end" tests are named in `package.json` like `specifier:test`:

https://github.com/JoshuaKGoldberg/create-typescript-app/blob/f9d63fc4f088f1b9c6c2be4f731a4d4e4f7880b3/package.json#L26

But the rest of the scripts generally adhere to a format like `area:specifier`, like:

https://github.com/JoshuaKGoldberg/create-typescript-app/blob/f9d63fc4f088f1b9c6c2be4f731a4d4e4f7880b3/package.json#L32

Let's switch them to `test:create`, test`:initialize`, and `test:migrate`. 

### Additional Info

You'll want to do a full text search on `:test`. At least `package.json` and some `.github/workflows/*.yml` files will need to be changed, as well as `.github/DEVELOPMENT.md`. And there should be at least one `.ts` file.

**Comment by DanexQ** [comment]
Can I work on this one?

**Comment by JoshuaKGoldberg** [comment]
For sure! See https://github.com/JoshuaKGoldberg/create-typescript-app/blob/b96c7b35946770f7b760c6a0afa67cdf105cf24a/.github/CONTRIBUTING.md#issue-claiming: no need to claim an issue, just sent a PR 🚀
