### ISSUE TITLE
🚀 Feature: Add accessibility-alt-text-bot GitHub Actions workflow

### ISSUE THREAD

**Issue by JoshuaKGoldberg** [JoshuaKGoldberg/create-typescript-app#825]
### Bug Report Checklist

- [X] I have tried restarting my IDE and the issue persists.
- [X] I have pulled the latest `main` branch of the repository.
- [X] I have [searched for related issues](https://github.com/JoshuaKGoldberg/create-typescript-app/issues?q=is%3Aissue) and found none that matched my issue.

### Overview

This is fantastic. Both for accessibility and folks posting giant screenshots of code in issues (always a blurgh).

https://github.blog/2023-06-12-make-your-github-projects-more-accessible-with-accessibility-alt-text-bot

### Additional Info

I believe this is blocked on https://github.com/github/accessibility-alt-text-bot/issues/28 & https://github.com/github/accessibility-alt-text-bot/issues/30, though.

**Comment by kendallgassner** [comment]
Unblocked! 😄
