### ISSUE TITLE
🐛 Bug: Crash trying to push --force up to GitHub

### ISSUE THREAD

**Issue by JoshuaKGoldberg** [JoshuaKGoldberg/create-typescript-app#907]
### Bug Report Checklist

- [X] I have tried restarting my IDE and the issue persists.
- [X] I have pulled the latest `main` branch of the repository.
- [X] I have [searched for related issues](https://github.com/JoshuaKGoldberg/create-typescript-app/issues?q=is%3Aissue) and found none that matched my issue.

### Expected

Creation mode should work to create a new repository.

### Actual

@KATT received a failure, reported in https://twitter.com/alexdotjs/status/1708175127991505291/photo/1:

```plaintext
Command failed with exit code 1: git push -u origin main --force
error: src refspec main does not match any
```

### Additional Info

@KATT if you have any more details on what you ran with, that could be very helpful.

In particular:

* Was this for a repository that didn't yet exist?
* Was the script able to make the repo on GitHub?

This seems vaguely similar to #691, but my gut is that this is a different issue.

**Comment by KATT** [comment]
I also noticed that it was created without a `test.yml`-file so I had to copy/paste that

**Comment by JoshuaKGoldberg** [comment]
I poked around and am pretty sure this is a side effect of #691. Closing to keep the issues queue small. Someone please yell at me if I'm wrong!
