### ISSUE TITLE
🚀 Feature: Infer --base from existing package.json scripts during migration

### ISSUE THREAD

**Issue by JoshuaKGoldberg** [JoshuaKGoldberg/create-typescript-app#933]
### Bug Report Checklist

- [X] I have tried restarting my IDE and the issue persists.
- [X] I have pulled the latest `main` branch of the repository.
- [X] I have [searched for related issues](https://github.com/JoshuaKGoldberg/create-typescript-app/issues?q=is%3Aissue) and found none that matched my issue.

### Overview

Right now, if you run `npx create-typescript-app` in an existing repository made from the template, you always get the standard mode selection:

```plaintext
◆  How much tooling would you like the template to set up for you?
│  ○ everything  The most comprehensive tooling imaginable: sorting, spellchecking, and more!
│  ● common      Bare starters plus testing and automation for all-contributors and releases. (recommended)
│  ○ minimum     Just bare starter tooling: building, formatting, linting, and type checking.
│  ○ prompt      (allow me to customize)
└
```

But as a convenience, we could set a default value for this based on `package.json`'s `scripts`.  Let's say:

1. If >=3 of the scripts listed under the _everything_ base exist, set the initial value to `everything`
2. If >=2 of the scripts listed under the _common_ base exist, set the initial value to `common`

**Comment by GV14982** [comment]
I'd like to take this, but I'm not quite understanding the potential solution. Could you give me an example please?

**Comment by JoshuaKGoldberg** [comment]
Absolutely - thanks for asking!

Suppose `npx create-typescript-app --mode migrate` (or, if running from a local build, `node path/to/create-typescript-app/bin/index.js --mode migrate`) is run in a directory that includes a `package.json` with the following `"scripts"`:

```json
{
	"scripts": {
		"build": "tsup",
		"format": "prettier \"**/*\" --ignore-unknown",
		"initialize": "tsx ./src/bin/index.js --mode initialize",
		"lint": "eslint . .*js --max-warnings 0",
		"lint:knip": "knip",
		"lint:md": "markdownlint \"**/*.md\" \".github/**/*.md\" --rules sentences-per-line",
		"lint:package-json": "npmPkgJsonLint .",
		"lint:packages": "pnpm dedupe --check",
		"lint:spelling": "cspell \"**\" \".github/**/*\"",
		"prepare": "husky install",
		"should-semantic-release": "should-semantic-release --verbose",
		"test": "vitest",
		"tsc": "tsc"
	}
}
```

The migration script could infer that the repo is probably using the _`"everything"`_ base (https://github.com/JoshuaKGoldberg/create-typescript-app/blob/main/docs/Options.md#base-and-mode). In that case it shouldn't need to ask for which `base` to use: https://github.com/JoshuaKGoldberg/create-typescript-app/blob/a51c624da09df2fefe7e2b12615a07f0a2457538/src/shared/options/augmentOptionsWithExcludes.ts#L135-L140

Does that answer what you're looking for?

**Comment by GV14982** [comment]
Ah yeah, that makes sense! Thanks for the explainer :)
