### ISSUE TITLE
🚀 Feature: Enable no-useless-rename

### ISSUE THREAD

**Issue by JoshuaKGoldberg** [JoshuaKGoldberg/create-typescript-app#939]
### Bug Report Checklist

- [X] I have tried restarting my IDE and the issue persists.
- [X] I have pulled the latest `main` branch of the repository.
- [X] I have [searched for related issues](https://github.com/JoshuaKGoldberg/create-typescript-app/issues?q=is%3Aissue) and found none that matched my issue.

### Overview

Once in a while I find a piece of code that unnecessarily renames a destructured variable:

https://github.com/JoshuaKGoldberg/create-typescript-app/blob/ef2e3483d851c8df2d4fdb2f7847d921a79f29b6/src/shared/options/ensureRepositoryExists.ts#L67

That `: github` part is unnecessary. The code is essentially the same as:

```diff
- return { github: github, repository };
+ return { github, repository };
```

https://eslint.org/docs/latest/rules/no-useless-rename exists but isn't enabled yet. Let's add it in!

### Additional Info

Note that there are multiple places you'll want to add `no-useless-rename`:

1. The repo's ESLint config: https://github.com/JoshuaKGoldberg/create-typescript-app/blob/ddf1318ca0302b458c9dc853d6252c2072fac802/.eslintrc.cjs#L162
2. The template for generating repo ESLint configs: https://github.com/JoshuaKGoldberg/create-typescript-app/blob/0b542be2a2c16dd225b739dbcf987b28ccd04a6f/src/steps/writing/creation/createESLintRC.ts#L210
3. Tests for ☝️ (`createESLintRC.test.ts`)

**Comment by DerTimonius** [comment]
I would love to take this!
