### ISSUE TITLE
🛠 Tooling: Is the 'if' in the accessibility-alt-text-bot workflow is needed?

### ISSUE THREAD

**Issue by JoshuaKGoldberg** [JoshuaKGoldberg/create-typescript-app#997]
### Bug Report Checklist

- [X] I have tried restarting my IDE and the issue persists.
- [X] I have pulled the latest `main` branch of the repository.
- [X] I have [searched for related issues](https://github.com/JoshuaKGoldberg/create-typescript-app/issues?q=is%3Aissue) and found none that matched my issue.

### Overview

Following up on @DerTimonius's https://github.com/JoshuaKGoldberg/create-typescript-app/pull/989#issuecomment-1784779035: we merged the PR with the `if`:

https://github.com/JoshuaKGoldberg/create-typescript-app/blob/0558e97d825b85466ef9bdab3d2bd1f303d76d80/.github/workflows/accessibility-alt-text-bot.yml#L5

...but I'm not sure that it's necessary. Are there events from GitHub's `on.(issue|issue_comment|pull_request)` that don't have `github.event.issue || github.event.pull_request`?

### Additional Info

This feels like something someone could probably answer by looking at the docs and/or experimenting in a temporary repository. But I haven't had the time to try. 😄 

Marking as `status: accepting prs` in case the answer is that the `if` is unnecessary. But if it is necessary, the right solution would be to close and wontfix this issue.

cc @kendallgassner as fyi / for visibility if you're curious

**Comment by kendallgassner** [comment]
Oh good point! I think this might be fallout from a refactor i'll file a bug on our end to check it out.

**Comment by DerTimonius** [comment]
I tried removing the `if` in a test repo, but there was no comment by the bot on [this issue](https://github.com/DerTimonius/a11y-bot-test/issues/1). So apparently it is necessary.

**Comment by kendallgassner** [comment]
This was surprising to me so I tested it on my end. I realized the README was out of date and if we bump to the latest version: `1.4.0` we do not need the if.

- [Related comment](https://github.com/github/accessibility-alt-text-bot/issues/38#issuecomment-1787758039)
- [Related PR](https://github.com/github/accessibility-alt-text-bot/pull/39)

**Comment by JoshuaKGoldberg** [comment]
Awesome thanks!
